### ISSUE TITLE
Qualtrics rankings don't appear until after interacting

### ISSUE THREAD

**Issue by taptapdan** [PERTS/silk#18]
@arnrow reported that Qualtrics rank type questions don't display the rank until after you start click-drag one of the options. We'd like them to display immediately. See screenshot below for example.

![qualtrics-rank-visibility](https://user-images.githubusercontent.com/276924/48436299-fab82f80-e743-11e8-9dcc-c343c49fdc69.gif)

Using Dev Tools > Inspect > Elements > Style, I determined that the following style exists:

```css
.Skin .RO .DND ul.NotEdited .rank {
    visibility: hidden;
}
```

Will change this so it's `visible`.
